version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
      - npm i @angular-devkit/build-angular
  build:
    commands:
      - echo Build started...
      - ng build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
